name: 2016.05.05
favicon: null
layout_spectrum: 0.49516
typography_spectrum: 0.7329749
title: '00100'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#ccd4d7'
    - '#9e9e9e'
    - '#443b32'
    - '#030403'
  brandStrength: 0.5035842
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
