name: 2016.05.05
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75594
title: '00100'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbbfc2'
    - '#737270'
    - '#4e4d4b'
    - '#000000'
    - '#e6f1f5'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.32234407821670175
purpose: []
